name: Build

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  pull_request:

env:
  CARGO_BIN_NAME: sjiswrap
  CARGO_TARGET_DIR: target

jobs:
  check:
    name: Check
    runs-on: windows-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cargo check
        run: cargo check --all-features --all-targets
      - name: Cargo clippy
        run: cargo clippy --all-features --all-targets

  fmt:
    name: Format
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        # We use nightly options in rustfmt.toml
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Cargo fmt
        run: cargo fmt --all --check

  build:
    name: Build
    strategy:
      matrix:
        include:
          - platform: windows-latest
            target: i686-pc-windows-msvc
            name: windows-x86
            build: build
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.packages != ''
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: Install cargo-zigbuild
        if: matrix.build == 'zigbuild'
        run: pip install ziglang==0.10.1.post1 cargo-zigbuild==0.17.0
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          targets: ${{ matrix.target }}
      - name: Cargo build
        run: cargo ${{ matrix.build }} --release --all-features --target ${{ matrix.target }} --bin ${{ env.CARGO_BIN_NAME }} -Z build-std=std,panic_abort
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ env.CARGO_TARGET_DIR }}/release/${{ env.CARGO_BIN_NAME }}
            ${{ env.CARGO_TARGET_DIR }}/release/${{ env.CARGO_BIN_NAME }}.exe
            ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/release/${{ env.CARGO_BIN_NAME }}
            ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/release/${{ env.CARGO_BIN_NAME }}.exe
          if-no-files-found: error

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Rename artifacts
        working-directory: artifacts
        run: |
          mkdir ../out
          for i in */*/release/$CARGO_BIN_NAME*; do
            mv "$i" "../out/$(sed -E "s/([^/]+)\/[^/]+\/release\/($CARGO_BIN_NAME)/\2-\1/" <<< "$i")"
          done
          ls -R ../out
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
